source 'https://github.com/luthfi11/Muvi-CorePodSpecs'

# Uncomment the next line to define a global platform for your project
# platform :ios, '14.5'

use_frameworks!

workspace 'Muvi'

target 'Muvi' do
  # Pods for Muvi
      pod 'RealmSwift'
      pod 'SDWebImageSwiftUI'
      pod 'Alamofire'
      pod 'Core'
end

target 'Common' do
   project '../Common/Common'
      pod 'RealmSwift'
      pod 'SDWebImageSwiftUI'
      pod 'Alamofire'
      pod 'Core'
end

target 'Home' do
   project '../Home/Home'
      pod 'RealmSwift'
      pod 'SDWebImageSwiftUI'
      pod 'Alamofire'
      pod 'Core'
end

target 'Detail' do
   project '../Detail/Detail'
      pod 'RealmSwift'
      pod 'SDWebImageSwiftUI'
      pod 'Alamofire'
      pod 'Core'
end

target 'Favorite' do
   project '../Favorite/Favorite'
      pod 'RealmSwift'
      pod 'SDWebImageSwiftUI'
      pod 'Alamofire'
      pod 'Core'
end

target 'Search' do
   project '../Search/Search'
      pod 'RealmSwift'
      pod 'SDWebImageSwiftUI'
      pod 'Alamofire'
      pod 'Core'
end

target 'About' do
   project '../About/About'
      pod 'SDWebImageSwiftUI'
end